# Dependencies
markdown:         kramdown
highlighter:      rouge

# Filtering Content
future:      false

# Outputting
paginate_path:    /page:num
paginate:         5
permalink:        pretty
timezone:         Europe/Paris

# Setup
title:            Side project me
tagline:          'A personal blog about a personal side project'
description:      'Un petit blog pour parler accompagner mon nouveau side project : des articles sur la conception, la réalisation, et la vie de celui-ci.'
url:              https://popofr13.github.io/sideprojectme/
baseurl:          /

author:
  name:           'Sebastien Porati'
  url:            https://twitter.com/popofr13

# Plugins
gems:             [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/popofr13/sideprojectme
